name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildlinux:
    runs-on: ubuntu-18.04
    steps:
    - name: ⏳ Checkout
      uses: actions/checkout@v2
    - name: 💿 Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: 💾 Cache .npm
      uses: actions/cache@v1
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-cache-npm-cache-${{ hashFiles('**/package-lock.json') }}
    - name: 💾 Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: 🚀 Build
      run: npm run compile
    - name: 🔢 Set version
      run: npm run setversion
    - name: 🎁 Package
      run: npm run package
    - name: 🌎 Publish
      uses: actions/upload-artifact@v2
      with:
        name: vscode-extension
        path: '*.vsix'