name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildlinux:
    runs-on: ubuntu-18.04
    steps:
    - name: ⏳ Checkout
      uses: actions/checkout@v2
    - name: 💿 Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: 🚀 Build
      run: npm run compile
    - name: 🎁 Package
      run: npm run package
    - name: 🌎 Publish
      uses: actions/upload-artifact@v2
      with:
        name: vscode-extension
        path: '*.vsix'