name: Build

on:
  push:
    branches: [ master, ship-grpc ]
  pull_request:
    branches: [ master ]

jobs:
  buildgrpcbinaries:
    strategy:
      matrix:
        runs-on: [ 'windows-2019', 'ubuntu-18.04', 'macos-10.15' ]
        electrum-version: [ '7.3.0', '7.2.0' ]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: ⏳ Checkout
      uses: actions/checkout@v2
    - name: 💿 Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: 💾 Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ matrix.electrum-version }}-build-grpc-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: 🚀 Build
      run: npm ci --target=${{ matrix.electrum-version }} --runtime=electron
    - name: 🌎 Publish
      uses: actions/upload-artifact@v2
      with:
        name: grpc-${{ matrix.runs-on }}-${{ matrix.electrum-version }}
        path: node_modules/grpc/src/node/extension_binary/*electron*/**/*
  buildlinux:
    runs-on: ubuntu-18.04
    needs: buildgrpcbinaries
    steps:
    - name: ⏳ Checkout
      uses: actions/checkout@v2
    - name: 💿 Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: 💾 Cache .npm
      uses: actions/cache@v1
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-cache-npm-cache-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/compile.js') }}
    - name: 💾 Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/compile.js') }}
    - name: 🚀 Build
      run: npm run compile
    - name: 🔢 Set version
      run: npm run setversion
    - name: 🎁 Package
      run: npm run package
    - name: 🗑 Artifact cleanup
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        expire-in: 24 hours
    - name: 🌎 Publish
      uses: actions/upload-artifact@v2
      with:
        name: vscode-extension
        path: '*.vsix'